### ISSUE TITLE
Usability in notebooks (jupyter / marimo)

### ISSUE THREAD

**Issue by hanckmann** [simon-ritchie/pconst#1]
First, this is a great idea and will actually help writing better code in Python.

However, it is very hard to use in jupyter / marimo notebooks because cells tend to be run multiple times (especially in marimo).

I would suggest to add an option checking for sameness. Hence, if the new object is the same as the old object, then the data will not be updated, but no error will be raised.
I realize there is the difficulty of how to compare objects. Here, I think, there could be two approaches:

1. only enable this feature for simple and/or immutable objects (numbers, strings, tuples, but not for lists, dicts, other items)
2. reply the objects build-in sameness check.

Option two is not fool-proof, but when clearly documented it could be sufficient.

I could fork and implement it in a new package, but maybe you are interested in such change as well.

**Comment by simon-ritchie** [comment]
@hanckmann 

LGTM.
I'll consider implementing it soon!

**Comment by simon-ritchie** [comment]
@hanckmann 

Supported this feature in version 1.1.1!

```
$ pip install pconst==1.1.1
```

You can set it with the `accept_same_value` method, like the following:

```py
from pconst import const

const.accept_same_value()
const.a = 100
const.a = 100
```

P.S. If you found this feature helpful, please leave a star on GitHub!
